# Generated by Django 4.2.6 on 2023-11-01 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email_Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_name', models.CharField(max_length=150)),
                ('User_email', models.EmailField(max_length=250)),
                ('User_subject', models.CharField(max_length=250)),
                ('User_message', models.TextField()),
                ('create_day', models.DateField()),
            ],
        ),
    ]
