# Generated by Django 4.2.6 on 2023-11-01 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Show', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email_content',
            name='create_day',
            field=models.DateField(auto_now=True),
        ),
    ]
